"use client";

import { ClerkProvider } from "@clerk/nextjs";
import { Outfit } from "next/font/google";
import { useState } from "react";
import { CartContext } from "./_context/CartContext";
import Header from "./components/Header";
import "./globals.css";
import Footer from "./components/Footer";

const inter = Outfit({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [cart, setCart] = useState([]);

  return (
    <ClerkProvider>
      <CartContext.Provider value={{ cart, setCart }}>
        <html lang="en">
          <body className={inter.className}>
            <Header />
            {children}
          </body>
          {/* <Footer /> */}
        </html>
      </CartContext.Provider>
    </ClerkProvider>
  );
}
